collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "layout_3"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "layout_2"
  - scope:
      path: ""
    values:
      layout: "layout_1"